### ISSUE TITLE
Rewrite function tests using `testing.FunctionTestCase`

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#6071]
We have introduced `testing.FunctionTestCase` (#3499).
This tool enables writing a function test for various backends (including ChainerX) in much simpler way.
This tool also provides an option to automatically dodge non-differentiable inputs.
We should apply this to all the existing function tests, and assure ChainerX support in those functions. 

~(Note: we should merge #6069 first to skip float16 in ChainerX backends.)~

## To get started
Please declare your will to work on a function, by posting a comment in this issue. If you're a collaborator, just write your name next to the function name.

### NumPy-compatible functions are not yet implemented
Write tentative implementation that falls back to numpy/cupy, in `chainerx/_fallback_workarounds.py`. For module-level functions (e.g. `chainerx.hstack`), write in `_populate_module_functions`. For `ndarray` methods, write in `_populate_ndarray`. Note that functions written in this way cannot support backprop in their own, but it's sufficient for computations in `FunctionNode.forward`, for example.
### Array type mismatch
In `FunctionNode` fallback (in which chainerx arrays are automatically converted to numpy/cupy and the corresponding `FunctionNode.forward` method is called), array attributes are also automatically converted between numpy/cupy and chainerx arrays. This is not the case if the array attribute is wrapped in a tuple, dict, etc. In this case, the attribute must be converted manually, using `backend.to_chainerx` and `backend.from_chainerx`.

76 done of 165 tests, 46% complete!

----

* [ ] functions_tests/pooling_tests/test_roi_max_align_2d.py
* [ ] functions_tests/pooling_tests/test_pooling_nd_kernel.py
* [ ] functions_tests/pooling_tests/test_max_pooling_2d.py
* [x] functions_tests/pooling_tests/test_unpooling_2d.py #6861
* [x] functions_tests/pooling_tests/test_average_pooling_2d.py #6211
* [ ] functions_tests/pooling_tests/test_roi_average_align_2d.py
* [ ] functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
* [ ] functions_tests/pooling_tests/test_roi_pooling_2d.py
* [ ] functions_tests/pooling_tests/test_roi_max_pooling_2d.py
* [x] functions_tests/pooling_tests/test_unpooling_nd.py #6861
* [ ] functions_tests/pooling_tests/test_roi_average_pooling_2d.py
* [x] functions_tests/pooling_tests/test_max_pooling_nd.py #3499
* [ ] functions_tests/pooling_tests/test_upsampling_2d.py
* [x] functions_tests/pooling_tests/test_average_pooling_nd.py #6332
* [x] functions_tests/normalization_tests/test_batch_renormalization.py #5817
* [ ] functions_tests/normalization_tests/test_local_response_normalization.py
* [ ] functions_tests/normalization_tests/test_batch_normalization.py
* [x] functions_tests/normalization_tests/test_layer_normalization.py #6871
* [ ] functions_tests/normalization_tests/test_group_normalization.py
* [ ] functions_tests/normalization_tests/test_l2_normalization.py
* [x] functions_tests/evaluation_tests/test_accuracy.py #7007
* [x] functions_tests/evaluation_tests/test_r2_score.py #7008
* [x] functions_tests/evaluation_tests/test_binary_accuracy.py
* [ ] functions_tests/evaluation_tests/test_classification_summary.py
* [x] functions_tests/loss_tests/test_mean_squared_error.py #5822 
* [ ] functions_tests/loss_tests/test_hinge.py
* [x] functions_tests/loss_tests/test_absolute_error.py #7281
* [ ] functions_tests/loss_tests/test_huber_loss.py
* [ ] functions_tests/loss_tests/test_negative_sampling.py
* [ ] functions_tests/loss_tests/test_contrastive.py
* [x] functions_tests/loss_tests/test_triplet.py #5819
* [ ] functions_tests/loss_tests/test_decov.py
* [x] functions_tests/loss_tests/test_mean_absolute_error.py #6253
* [ ] functions_tests/loss_tests/test_discriminative_margin_based_clustering_loss.py
* [ ] functions_tests/loss_tests/test_crf1d.py
* [ ] functions_tests/loss_tests/test_sigmoid_cross_entropy.py
* [ ] functions_tests/loss_tests/test_vae.py
* [x] functions_tests/loss_tests/test_softmax_cross_entropy.py #6363
* [ ] functions_tests/loss_tests/test_cross_covariance.py
* [ ] functions_tests/loss_tests/test_black_out.py
* [ ] functions_tests/loss_tests/test_ctc.py
* [ ] functions_tests/loss_tests/test_squared_error.py
* [x] functions_tests/activation_tests/test_hard_sigmoid.py #6192
* [x] functions_tests/activation_tests/test_log_softmax.py #6320 
* [x] functions_tests/activation_tests/test_softplus.py #6298
* [x] functions_tests/activation_tests/test_selu.py #6243 
* [ ] functions_tests/activation_tests/test_rrelu.py
* [x] functions_tests/activation_tests/test_prelu.py #6887
* [x] functions_tests/activation_tests/test_maxout.py #6302 
* [x] functions_tests/activation_tests/test_relu.py #3499
* [x] functions_tests/activation_tests/test_leaky_relu.py #6301 
* [x] functions_tests/activation_tests/test_elu.py #6070
* [ ] functions_tests/activation_tests/test_slstm.py
* [x] functions_tests/activation_tests/test_sigmoid.py
* [ ] functions_tests/activation_tests/test_lstm.py
* [x] functions_tests/activation_tests/test_softmax.py #6371 
* [x] functions_tests/activation_tests/test_swish.py
* [x] functions_tests/activation_tests/test_clipped_relu.py #3499
* [x] functions_tests/activation_tests/test_tanh.py #6173
* [x] functions_tests/activation_tests/test_crelu.py #6070 
* [ ] functions_tests/noise_tests/test_simplified_dropconnect.py
* [ ] functions_tests/noise_tests/test_zoneout.py
* [ ] functions_tests/noise_tests/test_dropout.py @niboshi 
* [ ] functions_tests/noise_tests/test_gaussian.py
* [ ] functions_tests/noise_tests/test_gumbel_softmax.py
* [x] functions_tests/math_tests/test_sign.py #6898
* [ ] functions_tests/math_tests/test_scale.py #6969 
* [x] functions_tests/math_tests/test_ceil.py #6900
* [ ] functions_tests/math_tests/test_det.py
* [x] functions_tests/math_tests/test_polygamma.py #6970 
* [x] functions_tests/math_tests/test_logsumexp.py #7018
* [ ] functions_tests/math_tests/test_erf.py
* [ ] functions_tests/math_tests/test_log_ndtr.py
* [x] functions_tests/math_tests/test_floor.py #6901
* [x] functions_tests/math_tests/test_exponential_m1.py #6965
* [x] functions_tests/math_tests/test_tensordot.py #6968
* [ ] functions_tests/math_tests/test_ndtri.py
* [x] functions_tests/math_tests/test_prod.py #6479 
* [x] functions_tests/math_tests/test_fmod.py #6937
* [ ] functions_tests/math_tests/test_erfcinv.py
* [ ] functions_tests/math_tests/test_ndtr.py
* [ ] functions_tests/math_tests/test_erfcx.py
* [x] functions_tests/math_tests/test_exponential.py #6963
* [x] functions_tests/math_tests/test_linear_interpolate.py #6984
* [x] functions_tests/math_tests/test_logarithm_1p.py #6981 
* [x] functions_tests/math_tests/test_maximum.py #6400 
* [ ] functions_tests/math_tests/test_einsum.py
* [x] functions_tests/math_tests/test_cumsum.py #6977
* [x] functions_tests/math_tests/test_minmax.py #6962
* [ ] functions_tests/math_tests/test_lgamma.py
* [ ] functions_tests/math_tests/test_trigonometric.py
* [x] functions_tests/math_tests/test_average.py #6995 
* [x] functions_tests/math_tests/test_cumprod.py #6978 
* [ ] functions_tests/math_tests/test_sqrt.py
* [x] functions_tests/math_tests/test_matmul.py #6987
* [ ] functions_tests/math_tests/test_erfc.py
* [x] functions_tests/math_tests/test_batch_l2_norm_squared.py #6996
* [x] functions_tests/math_tests/test_minimum.py #6396 
* [x] functions_tests/math_tests/test_hyperbolic.py #6980 
* [x] functions_tests/math_tests/test_fft.py #6985
* [x] functions_tests/math_tests/test_squared_difference.py #6395 
* [ ] functions_tests/math_tests/test_erfinv.py
* [ ] functions_tests/math_tests/test_digamma.py
* [ ] functions_tests/math_tests/test_clip.py
* [ ] functions_tests/math_tests/test_square.py
* [x] functions_tests/math_tests/test_inv.py #6994
* [ ] functions_tests/math_tests/test_sparse_matmul.py
* [x] functions_tests/math_tests/test_sum.py #6307 
* [x] functions_tests/math_tests/test_bias.py #6976 
* [ ] functions_tests/math_tests/test_basic_math.py
* [x] functions_tests/math_tests/test_fix.py #6938
* [ ] functions_tests/array_tests/test_broadcast.py
* [x] functions_tests/array_tests/test_vstack.py #6410 
* [x] functions_tests/array_tests/test_repeat.py #6803
* [x] functions_tests/array_tests/test_swapaxes.py #6460 
* [x] functions_tests/array_tests/test_expand_dims.py #6473 
* [x] functions_tests/array_tests/test_separate.py #7013
* [x] functions_tests/array_tests/test_reshape.py #6868
* [x] functions_tests/array_tests/test_where.py #6802
* [x] functions_tests/array_tests/test_flipud.py #6390 
* [ ] functions_tests/array_tests/test_spatial_transformer_grid.py
* [x] functions_tests/array_tests/test_diagonal.py #6322 
* [x] functions_tests/array_tests/test_resize_images.py #6464 
* [ ] functions_tests/array_tests/test_pad_sequence.py
* [x] functions_tests/array_tests/test_rollaxis.py #6408 
* [x] functions_tests/array_tests/test_split_axis.py #3499
* [x] functions_tests/array_tests/test_permutate.py #7010
* [ ] functions_tests/array_tests/test_transpose_sequence.py
* [x] functions_tests/array_tests/test_transpose.py #6458 
* [x] functions_tests/array_tests/test_pad.py #6393 
* [ ] functions_tests/array_tests/test_select_item.py
* [x] functions_tests/array_tests/test_flatten.py #6888
* [x] functions_tests/array_tests/test_squeeze.py #6487 
* [x] functions_tests/array_tests/test_hstack.py #3499
* [ ] functions_tests/array_tests/test_depth_2_space.py
* [ ] functions_tests/array_tests/test_space_2_depth.py
* [x] functions_tests/array_tests/test_moveaxis.py #6392 
* [x] functions_tests/array_tests/test_scatter_add.py #7012
* [x] functions_tests/array_tests/test_tile.py #6459 
* [x] functions_tests/array_tests/test_fliplr.py #6389 
* [ ] functions_tests/array_tests/test_im2col.py
* [x] functions_tests/array_tests/test_concat.py #5823
* [ ] functions_tests/array_tests/test_copy.py @niboshi 
* [ ] functions_tests/array_tests/test_cast.py #7034
* [ ] functions_tests/array_tests/test_stack.py
* [ ] functions_tests/array_tests/test_spatial_transformer_sampler.py
* [x] functions_tests/array_tests/test_flip.py #6801
* [x] functions_tests/array_tests/test_dstack.py #6891
* [x] functions_tests/array_tests/test_get_item.py #6990
* [x] functions_tests/connection_tests/test_linear.py #6236
* [ ] functions_tests/connection_tests/test_deformable_convolution_2d_sampler.py
* [ ] functions_tests/connection_tests/test_embed_id.py
* [ ] functions_tests/connection_tests/test_convolution_nd.py #6406 
* [ ] functions_tests/connection_tests/test_dilated_convolution_2d.py
* [ ] functions_tests/connection_tests/test_n_step_gru.py
* [ ] functions_tests/connection_tests/test_depthwise_convolution_2d.py
* [ ] functions_tests/connection_tests/test_n_step_rnn.py
* [ ] functions_tests/connection_tests/test_shift.py
* [ ] functions_tests/connection_tests/test_convolution_2d.py #6406 
* [ ] functions_tests/connection_tests/test_deconvolution_2d.py #6498 
* [ ] functions_tests/connection_tests/test_bilinear.py #6488 
* [ ] functions_tests/connection_tests/test_n_step_lstm.py
* [ ] functions_tests/connection_tests/test_local_convolution_2d.py
* [ ] functions_tests/connection_tests/test_deconvolution_nd.py #6500 
* [ ] functions_tests/util_tests/test_forget.py

**Comment by crcrpar** [comment]
I'm working on tanh (#6173) and sigmoid (#6174)

**Comment by crcrpar** [comment]
https://github.com/chainer/chainer/pull/6139/ rewrote the tests of `F.rrelu`.

**Comment by aksub99** [comment]
I'd like to work on test_softmax_cross_entropy (loss) and test_softmax (activation).

**Comment by aksub99** [comment]
I'm also working on test_mean_absolute_error.

**Comment by niboshi** [comment]
@crcrpar @aksub99 
Thank you!

**Comment by ishanrai05** [comment]
@niboshi  Please review my PR.

**Comment by niboshi** [comment]
@ishanrai05 Thanks! Please wait until a reviewer will be assigned soon.

**Comment by aksub99** [comment]
I have submitted the above PRs  to simplify test_leaky_relu.py and test_maxout.py. Am still working on fixing test_softmax.py and test_mean_absolute_error.py.

**Comment by ishanrai05** [comment]
I have submitted PRs to simplify `test_swish` and `test_softpool`.

**Comment by aksub99** [comment]
@niboshi Could you please review PRs #6301 and #6302 ?

**Comment by ishanrai05** [comment]
I have submitted PR #6320 to simplify `test_log_softmax`

**Comment by ishanrai05** [comment]
Submitted PR #6322  for `test_diagonal`

**Comment by stegben** [comment]
Hi, I'm new to this repo, may I work on `math_tests.test_sqrt` first?

**Comment by sameshl** [comment]
If this issue still needs work, I would love to take it up

**Comment by crcrpar** [comment]
@sameshl I think so. Note that the list in the first post might be obsolete.

**Comment by UmashankarTriforce** [comment]
I would like toi know if the list provided is updated. If yes, I'd like to work on them

**Comment by UmashankarTriforce** [comment]
May I know the status of this issue? I would like to work on this, if it is still open.

**Comment by andy6975** [comment]
I would like to work on squared error and sqrt tests. Could anyone give me a headstart, I relatively new in chainer contribution community. Thanks!
