### ISSUE TITLE
Fix test flakiness

### ISSUE THREAD

**Issue by imos** [chainer/chainer#6903]
There are many flaky tests, and leaving them as is not healthy for Chainer repository. I'd like to suggest they should be fixed. The following is the list of flaky tests (I may update this later).

- [x] #6841 chainer_tests/functions_tests/activation_tests/test_elu.py
  - Failure example: https://ci.preferred.jp/chainer.py37/2131/
- [x] #6904 chainer_tests/functions_tests/activation_tests/test_rrelu.py
  - Failure example: https://ci.preferred.jp/chainer.py27and35/2279/
- [x] #6905 chainer_tests/functions_tests/array_tests/test_spatial_transformer_sampler.py
  - Failure example: https://ci.preferred.jp/chainer.py27and35/2070/
- [x] #6906 chainer_tests/functions_tests/loss_tests/test_huber_loss.py
  - Failure example: https://ci.preferred.jp/chainer.py27and35/2312/
- [x] #6855 chainer_tests/functions_tests/loss_tests/test_triplet.py
  - Failure example: https://ci.preferred.jp/chainer.py27and35/2150/
- [x] #6845 chainer_tests/functions_tests/math_tests/test_erfc.py
  - Failure example: https://ci.preferred.jp/chainer.py27and35/2136/
- [x] #6907 chainer_tests/functions_tests/math_tests/test_tensordot.py
  - Failure example: https://ci.preferred.jp/chainer.py27and35/2328/
- [x] #6908 chainer_tests/functions_tests/normalization_tests/test_decorrelated_batch_normalization.py
  - Failure example: https://ci.preferred.jp/chainer.py27and35/2072/
- [x] #6909 chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
  - Failure example: https://ci.preferred.jp/chainer.py37/2267/
- [x] #6910 chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py
  - Failure example: https://ci.preferred.jp/chainer.py37/2214/
- [x] #6911 chainer_tests/links_tests/normalization_tests/test_group_normalization.py
  - Failure example: https://ci.preferred.jp/chainer.py27and35/2138/
- [x] #6912 chainerx_tests/unit_tests/routines_tests/test_math.py
  - Failure example: https://ci.preferred.jp/chainer.py37/2259/
- [x] #6913 chainerx_tests/unit_tests/routines_tests/test_normalization.py
  - Failure example: https://ci.preferred.jp/chainer.py37/2261/
- [x] #6914 chainerx_tests/unit_tests/routines_tests/test_pooling.py
  - Failure example: https://ci.preferred.jp/chainer.py37/2131/
- [x] #7686 `chainerx_tests/unit_tests/routines_tests/test_connection.py::test_ConvTransposeTensorCore`
- [x]  #7690 `TestAdam_param_3_{adabound=False, amsgrad=False, dtype=float16, loss_scaling='static', use_placeholder=True}.test_linear_model_multi_gpu`
- [x] #7693 tests/chainer_tests/links_tests/connection_tests/test_deconvolution_2d.py
- [x] #7695 tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
- [x] #7696 tests/chainerx_tests/unit_tests/routines_tests/test_loss.py
- [x] #7701 `chainerx_tests/unit_tests/routines_tests/test_explog.py::test_Erf`
- [x] #7702 `chainerx_tests/unit_tests/routines_tests/test_arithmetic.py::test_Power`
- [x] #7703 `TestAveragePooling2D`
- [x] #7704 `chainer_tests/functions_tests/loss_tests/test_contrastive.py::TestContrastive`
- [x] #7737 `chainerx_tests/unit_tests/routines_tests/test_trigonometric_hyperbolic.py::test_Arcsin`
- [x] #7785 `chainerx_tests/unit_tests/routines_tests/test_arithmetic.py::test_TrueDivide`
- [x] #7809 `chainerx_tests/unit_tests/routines_tests/test_creation.py::test_TrilTriu`
- [x] #7819 `chainer_tests/functions_tests/evaluation_tests/test_accuracy.py`
- [x]  #7845 `chainerx_tests/unit_tests/routines_tests/test_arithmetic.py::test_Sub`
- [x] #7861 `tests/chainerx_tests/unit_tests/routines_tests/test_reduction.py::test_LogSumExp`
- [x] #7892 `chainer_tests/functions_tests/array_tests/test_cast.py::TestCast`
- [x] #7911 `TestMaxPooling2D`
- [x] #7914 `TestFmod`
- [x] #7925 `tests/chainer_tests/links_tests/loss_tests/test_crf1d.py::TestCRF1d`
- [x] #7946 `tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py::TestConvolution2DFunction`
- [x] #7958 `tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py::TestNegativeSamplingFunction`
- [x] #7969 `tests/chainer_tests/functions_tests/math_tests/test_inv.py::BatchInvFunctionTest`
- [x] https://github.com/chainer/chainer/issues/7973 `tests/chainer_tests/test_gradient_check.py::TestCheckBackwardNoneConvention`
- [x] #7976 `chainerx_tests/unit_tests/routines_tests/test_linalg.py::test_Solve`
- [x] #7986 `chainerx_tests/unit_tests/routines_tests/test_linalg.py::test_PseudoInverse`
- [x] #7993 `tests/chainerx_tests/unit_tests/routines_tests/test_misc.py::test_Maximum`
- [x] #8008 `chainer_tests/functions_tests/loss_tests/test_squared_error.py::TestSquaredError`
- [x] #8024 `chainer_tests/functions_tests/loss_tests/test_triplet.py::TestTriplet`
- [x] #8025 `chainer_tests/test_gradient_check.py::TestCheckBackward::test_const_input`
- [x] #8026 `tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py::test_QR`
- [x] #8032 `tests/chainerx_tests/unit_tests/routines_tests/test_rnn.py::test_NStepRNN`
- [x] #8033 `tests/chainerx_tests/unit_tests/routines_tests/test_rnn.py::test_NStepBiRNN`
- [x] #8034 `tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py::test_Inverse`
- [x] #8035 `tests/chainer_tests/functions_tests/array_tests/test_im2col.py::TestIm2Col`
- [x] #8083 `chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py::TestL2Normalization`
- [x] #8093  `tests/chainer_tests/test_variable.py:: TestVariableDoubleBackwardOneElementScalar `
- [x] #8094 `tests/chainer_tests/functions_tests/math_tests/test_basic_math.py::TestVariableConstantArrayOp`
- [x] #8095 `tests/chainer_tests/test_gradient_check.py::test_multiple_output`
- [x] #8116 `chainer_tests/functions_tests/connection_tests/test_convolution_2d.py::TestConvolution2DFunction::test_double_backward`
- [x] #8145 `chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py::TestBatchNormalization::test_backward`
- [x]  #8151 `chainer_tests/functions_tests/array_tests/test_cast.py::TestNoCast::test_forward_no_cast_grad`
- [x] #8162 `chainer_tests/testing_tests/test_function_link.py::TestLinkIncorrectBackwardInput`
- [x] #8166 `test_zeta` 
- [x] #8181 `chainer_tests/serializers_tests/test_hdf5.py::TestHDF5Deserializer::test_deserialize_different_dtype_cpu`
- [x]  #8199 `chainerx_tests/unit_tests/routines_tests/test_normalization.py::test_BatchNorm`
- [x] #8237 `chainerx_tests/unit_tests/routines_tests/test_linalg.py::test_SVD`
- [x] #8268 `tests/chainerx_tests/unit_tests/routines_tests/test_creation.py::test_Meshgrid`
- [x] #8274 `Flaky test: tests/chainerx_tests/unit_tests/routines_tests/test_rnn.py test_NStepGru`
- [x] #8289 `chainer_tests/functions_tests/loss_tests/test_negative_sampling.py`
- [x] #8315 `chainerx_tests/unit_tests/routines_tests/test_loss.py::test_SoftmaxCrossEntropy`
- [x] #8316 `chainerx_tests/unit_tests/routines_tests/test_indexing.py::test_WhereScalar`
- [x] #8362 `chainerx_tests/unit_tests/routines_tests/test_linalg.py::test_CholeskyFailing`
- [x] #8366 `chainerx_tests/unit_tests/routines_tests/test_arithmetic.py::test_IRemainder`
- [x] #8374 `chainer_tests/functions_tests/array_tests/test_where.py::TestWhere`
- [x] #8390 `chainer_tests/distributions_tests/test_utils.py::TestModifiedXLogX`
- [x] #8425 (timeout) `chainerx_tests/unit_tests/routines_tests/test_linalg.py`
- [x] #8430 `chainermn_tests/extensions_tests/test_multi_node_snapshot.py::test_multinode_autoload`
- [x] #8481 `chainer_tests/functions_tests/math_tests/test_cholesky.py`
- [x] #8512 `chainer_tests/functions_tests/loss_tests/test_decov.py`
- [x] #8519 `chainerx_tests/unit_tests/routines_tests/test_statistics.py::test_Max`

**Comment by beam2d** [comment]
I changed the category to "test" because this issue itself is about fixing tests. Individual child issues may include bug fixes in which case they might be labeled "bug".

**Comment by niboshi** [comment]
https://travis-ci.org/chainer/chainer/jobs/529891620
```
FAIL tests/chainerx_tests/unit_tests/routines_tests/test_math.py::test_TrueDivide_param_69_{in_dtypes=('float16', 'float16'), is_module=False, in_shapes=((3, 1), (1, 4)), out_dtype='float16', input_lhs='random', input_rhs='random'}[native:0]
```

**Comment by niboshi** [comment]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/889/TEST=chainer-py3,label=mn1-p100/console

```
11:22:18 __ TestModifiedXLogX_param_0_{dtype=float32, shape=(2, 3)}.test_backward_gpu ___
11:22:18 
11:22:18 self = <chainer.testing._bundle.TestModifiedXLogX_param_0_{dtype=float32, shape=(2, 3)} testMethod=test_backward_gpu>
11:22:18 
11:22:18     @attr.gpu
11:22:18     def test_backward_gpu(self):
11:22:18 >       self.check_backward(cuda.to_gpu(self.x), cuda.to_gpu(self.gy))
11:22:18 
11:22:18 self       = <chainer.testing._bundle.TestModifiedXLogX_param_0_{dtype=float32, shape=(2, 3)} testMethod=test_backward_gpu>
11:22:18 
11:22:18 tests/chainer_tests/distributions_tests/test_utils.py:47: 
11:22:18 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
11:22:18 tests/chainer_tests/distributions_tests/test_utils.py:40: in check_backward
11:22:18     x_data, y_grad, **self.backward_options)
11:22:18 chainer/gradient_check.py:894: in check_backward
11:22:18     detect_nondifferentiable, is_immutable_params=False
11:22:18 chainer/gradient_check.py:466: in run
11:22:18     self._run()
11:22:18 chainer/gradient_check.py:509: in _run
11:22:18     self._compare_gradients(gx_numeric, gx_backward, directions)
11:22:18 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
11:22:18 
11:22:18 self = <chainer.gradient_check._CheckBackward object at 0x7fa59d6d2be0>
11:22:18 gx_numeric = array(0.04649969), gx_backward = array(0.03557094)
11:22:18 directions = [array([[ 0.18987038, -0.2352165 ,  0.25350259],
11:22:18        [-0.75605759,  0.11606058,  0.50918144]])]
11:22:18 
11:22:18     def _compare_gradients(self, gx_numeric, gx_backward, directions):
11:22:18         atol = self.atol
11:22:18         rtol = self.rtol
11:22:18         # Compare the gradients
11:22:18         try:
11:22:18             testing.assert_allclose(
11:22:18                 gx_numeric, gx_backward, atol=atol, rtol=rtol)
11:22:18         except AssertionError as e:
11:22:18             eps = self.eps
11:22:18             xs = self.xs
11:22:18             gys = self.gys
11:22:18             f = six.StringIO()
11:22:18             f.write('check_backward failed (eps={} atol={} rtol={})\n'.format(
11:22:18                 eps, atol, rtol))
11:22:18             for i, x in enumerate(xs):
11:22:18                 f.write('inputs[{}]:\n'.format(i))
11:22:18                 f.write('{}\n'.format(x))
11:22:18             for i, gy in enumerate(gys):
11:22:18                 f.write('grad_outputs[{}]:\n'.format(i))
11:22:18                 f.write('{}\n'.format(gy))
11:22:18             for i, d in enumerate(directions):
11:22:18                 f.write('directions[{}]:\n'.format(i))
11:22:18                 f.write('{}\n'.format(d))
11:22:18             f.write('gradients (numeric):  {}\n'.format(gx_numeric))
11:22:18             f.write('gradients (backward): {}\n'.format(gx_backward))
11:22:18             f.write('\n')
11:22:18             f.write('x: numeric gradient, y: backward gradient')
11:22:18             f.write(str(e))
11:22:18 >           raise AssertionError(f.getvalue())
11:22:18 E           AssertionError: Parameterized test failed.
11:22:18 E           
11:22:18 E           Base test method: TestModifiedXLogX.test_backward_gpu
11:22:18 E           Test parameters:
11:22:18 E             dtype: <class 'numpy.float32'>
11:22:18 E             shape: (2, 3)
11:22:18 E           
11:22:18 E           
11:22:18 E           (caused by)
11:22:18 E           AssertionError: check_backward failed (eps=1e-05 atol=0.01 rtol=0.01)
11:22:18 E           inputs[0]:
11:22:18 E           [[0.7410431  0.47612515 0.9824761 ]
11:22:18 E            [0.644881   0.95344114 0.15098213]]
11:22:18 E           grad_outputs[0]:
11:22:18 E           [[ 0.4162284  -0.86797017  0.73351467]
11:22:18 E            [-1.0928663  -2.312499    1.0216523 ]]
11:22:18 E           directions[0]:
11:22:18 E           [[ 0.18987038 -0.2352165   0.25350259]
11:22:18 E            [-0.75605759  0.11606058  0.50918144]]
11:22:18 E           gradients (numeric):  0.046499694139612295
11:22:18 E           gradients (backward): 0.035570936293422645
11:22:18 E           
11:22:18 E           x: numeric gradient, y: backward gradient
11:22:18 E           Not equal to tolerance rtol=0.01, atol=0.01
11:22:18 E           
11:22:18 E           Mismatch: 100%
11:22:18 E           Max absolute difference: 0.01092876
11:22:18 E           Max relative difference: 0.30723841
11:22:18 E            x: array(0.0465)
11:22:18 E            y: array(0.035571)
11:22:18 E           
11:22:18 E           assert_allclose failed: 
11:22:18 E             shape: () ()
11:22:18 E             dtype: float64 float64
11:22:18 E             i: (0,)
11:22:18 E             x[i]: 0.046499694139612295
11:22:18 E             y[i]: 0.035570936293422645
11:22:18 E             relative error[i]: 0.30723840823415344
11:22:18 E             absolute error[i]: 0.01092875784618965
11:22:18 E           x: 0.04649969
11:22:18 E           y: 0.03557094
11:22:18 
11:22:18 atol       = 0.01
11:22:18 d          = array([[ 0.18987038, -0.2352165 ,  0.25350259],
11:22:18        [-0.75605759,  0.11606058,  0.50918144]])
11:22:18 directions = [array([[ 0.18987038, -0.2352165 ,  0.25350259],
11:22:18        [-0.75605759,  0.11606058,  0.50918144]])]
11:22:18 eps        = 1e-05
11:22:18 f          = <_io.StringIO object at 0x7fa59d8a4dc8>
11:22:18 gx_backward = array(0.03557094)
11:22:18 gx_numeric = array(0.04649969)
11:22:18 gy         = array([[ 0.4162284 , -0.86797017,  0.73351467],
11:22:18        [-1.0928663 , -2.312499  ,  1.0216523 ]], dtype=float32)
11:22:18 gys        = (array([[ 0.4162284 , -0.86797017,  0.73351467],
11:22:18        [-1.0928663 , -2.312499  ,  1.0216523 ]], dtype=float32),)
11:22:18 i          = 0
11:22:18 rtol       = 0.01
11:22:18 self       = <chainer.gradient_check._CheckBackward object at 0x7fa59d6d2be0>
11:22:18 x          = array([[0.7410431 , 0.47612515, 0.9824761 ],
11:22:18        [0.644881  , 0.95344114, 0.15098213]], dtype=float32)
11:22:18 xs         = (array([[0.7410431 , 0.47612515, 0.9824761 ],
11:22:18        [0.644881  , 0.95344114, 0.15098213]], dtype=float32),)
11:22:18 
11:22:18 chainer/gradient_check.py:539: AssertionError
```

**Comment by niboshi** [comment]
https://travis-ci.org/chainer/chainer/jobs/539622517
```
FAIL tests/chainer_tests/distributions_tests/test_utils.py::TestModifiedXLogX_param_0_{shape=(2, 3), dtype=float32}::test_backward_cpu
```
```
E           AssertionError: Parameterized test failed.
E           
E           Base test method: TestModifiedXLogX.test_backward_cpu
E           Test parameters:
E             shape: (2, 3)
E             dtype: <class 'numpy.float32'>
E           
E           
E           (caused by)
E           AssertionError: check_backward failed (eps=1e-05 atol=0.01 rtol=0.01)
E           inputs[0]:
E           [[0.66583544 0.66731167 0.7417773 ]
E            [0.89922833 0.27608615 0.86474884]]
E           grad_outputs[0]:
E           [[ 0.56588167  2.1651914  -0.10487275]
E            [ 1.04816    -0.98743844 -2.3347232 ]]
E           directions[0]:
E           [[ 0.07101393 -0.43770988 -0.68181427]
E            [-0.01985378 -0.49688141 -0.30201171]]
E           gradients (numeric):  -0.03641638879336995
E           gradients (backward): -0.04717040343175993
E           
E           x: numeric gradient, y: backward gradient
E           Not equal to tolerance rtol=0.01, atol=0.01
E           
E           (mismatch 100.0%)
E            x: array(-0.036416)
E            y: array(-0.04717)
E           
E           assert_allclose failed: 
E             shape: () ()
E             dtype: float64 float64
E             i: (0,)
E             x[i]: -0.03641638879336995
E             y[i]: -0.04717040343175993
E             relative error[i]: 0.22798224852894272
E             absolute error[i]: 0.010754014638389986
E           x: -0.03641639
E           y: -0.0471704
```

**Comment by kmaehashi** [comment]
We finally solved all flaky tests!
