### ISSUE TITLE
Support ChainerX in each optimizer hook implementation

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7634]
Part of #7541

* [x] `gradient_clipping.py` #7640
* [x] `gradient_hard_clipping.py` #7656
* [x] `gradient_lars.py` #7669
* [x] `gradient_noise.py`#7709
* [x] `lasso.py`  #7657
* [x] `weight_decay.py` #7716
