### ISSUE TITLE
Support NumPy 1.17

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#7741]
- [x] Output dtype of `np.clip` (numpy/numpy#12519)
  - [x] `chainer_tests/functions_tests/activation_tests/test_clipped_relu.py` #7842
    * [x] backport
  - [x] `chainer_tests/functions_tests/loss_tests/test_huber_loss.py` #7843
  - [x] `chainer_tests/functions_tests/math_tests/test_clip.py` #7843
    * [x] backport
- [x] https://github.com/chainer/chainer-test/pull/515
- [x] https://github.com/cupy/cupy/issues/2361
- [x] https://github.com/cupy/cupy/issues/2370
- [x] Fix documentation on supported Numpy versions
  - [x] chainer (master: #7883, stable: #7961)
  - [x] cupy (master: https://github.com/cupy/cupy/pull/2368, stable: https://github.com/cupy/cupy/pull/2413)

(The list may not be comprehensive.)

**Comment by kmaehashi** [comment]
Will close after confirming Jenkins is not failing.
